### ISSUE TITLE
Can't launch programs through mirror

### ISSUE THREAD

**Issue by MythicManiac** [dokan-dev/dokan-dotnet#77]
If I try to launch programs through the mirror, I either end up with `<program>.exe is not a valid Win32 application` or it manages to start and instantly crashes.

I've tried launching several different programs this way (also with the C mirror), but none of them have launched properly.

Haven't noticed anything suspicious in the debug output either.

I'm mirroring the whole `C:\` drive, so it shouldn't matter if the programs use absolute or relative paths to locate their stuff, as it should map to the same place anyway.

**Comment by Liryna** [comment]
Hi @MythicManiac ,

With the C Mirror it should work (we had issue before but they have been fixed).
DId you try to start the mirror with admin rights ?

**Comment by MythicManiac** [comment]
Tried again, this time running it as an administrator, still facing the same issue.

Notepad++ seems to be able to launch, but that's the only one that I have found working so far.

It should be mentioned that I'm using the pre-release version.

**Comment by MythicManiac** [comment]
Some of the error messages I'm getting from the applications:
![image](https://cloud.githubusercontent.com/assets/8225825/14298092/9a975b9a-fb8b-11e5-90e4-e6f3f89d5568.png)
![image](https://cloud.githubusercontent.com/assets/8225825/14298098/a28f41d2-fb8b-11e5-88e6-6e206996f222.png)
![image](https://cloud.githubusercontent.com/assets/8225825/14298105/acb34b7c-fb8b-11e5-9474-9b2affb1b33c.png)
![image](https://cloud.githubusercontent.com/assets/8225825/14298113/b9055c12-fb8b-11e5-8759-714b778901ce.png)
![image](https://cloud.githubusercontent.com/assets/8225825/14298130/ce1f1688-fb8b-11e5-8c0e-d52512125d3e.png)
![image](https://cloud.githubusercontent.com/assets/8225825/14298142/ddd3c6c8-fb8b-11e5-86e1-69915adb8748.png)

I ran `mirror.exe /r C:\ /l L /t 5 /d /C` from an administrator privileged command prompt.

**Comment by MythicManiac** [comment]
Notepad++ seems to have roughly a 50% success in launching, but the other 50% of the time it fails like the rest:
![image](https://cloud.githubusercontent.com/assets/8225825/14298220/6b78300e-fb8c-11e5-8b74-1406d385f410.png)
![image](https://cloud.githubusercontent.com/assets/8225825/14298247/8bc883f4-fb8c-11e5-811b-54a8f6da3968.png)

**Comment by Maxhy** [comment]
@MythicManiac @Liryna this was fixed on current 1.0.0 coming release, latest stable release 0.8.0 doesn't have this fix. I believe you're using this one right?

**Comment by MythicManiac** [comment]
https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-RC2 This is the release I'm using of Dokany, and the DotNet wrapper I have was installed with `Install-Package DokanNet -Pre` on the package manager console.

**Comment by Liryna** [comment]
I had no time to test with the RC2 for now but I made a test with the last dokan commit that I have build and installed
![test](https://cloud.githubusercontent.com/assets/4311419/14327974/fe38d012-fc34-11e5-8837-95ece21d62d2.png)

I face no issue by running notepad++, NSIS and even iexplorer.exe

It is possible that since RC2 there is some changes that fixed what you face but I still doubt about it :(

I have never had the behaviour you describe.

**Comment by MythicManiac** [comment]
@Liryna could you try launching some application that heavily relies on DirectX / OpenGL through it?

I could try if downgrading would fix my problem, but I doubt it.

**Comment by Liryna** [comment]
I don't have games installed on my system sorry :'(
But I started Visual Studio directly and it worked.
`L:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe`

![test](https://cloud.githubusercontent.com/assets/4311419/14329065/0386f346-fc3a-11e5-83fb-403e8fe668b5.png)
![test](https://cloud.githubusercontent.com/assets/4311419/14329080/15943c60-fc3a-11e5-8e79-c6cb17cd70d2.png)

**Comment by MythicManiac** [comment]
I tested with my VS2015 as well, sometimes it launched properly, sometimes it hanged, and sometimees it got pretty much the same errors as the ones I posted earlier.

Is there a way to have the mirror output log to a file directly? Window's cmd printing is really slow with large amounts of data

**Comment by Liryna** [comment]
You can try with `mirror.exe > a.txt 2>&1`

**Comment by MythicManiac** [comment]
Heres a [log.txt](https://github.com/dokan-dev/dokan-dotnet/files/207176/log.txt) where I failed to start League of Legends a few times (Also Windows crashed after unmounting while I still had a process left hanging through the mirror :+1:)

What do you mean with a simple hello world?

**Comment by Liryna** [comment]
Build and run something like:
```
/* Hello World program */

#include<stdio.h>

main()
{
    printf("Hello World");


}
```

Crashed after unmounting ? thats interesting!
Could you give the report analyse of the memory dump ?
https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod

**Comment by MythicManiac** [comment]
Just to confirm: did you mean I should run a basic hello world through the mirror until I get an error?

As for the crash, I'm pretty sure it's supposed to happen and not a bug, because Windows was running a program through the mirror when I killed the mirror. Here's the [dump.txt](https://github.com/dokan-dev/dokan-dotnet/files/207313/dump.txt) anyway in case it helps you in any way.

**Comment by Maxhy** [comment]
I'm not sure you're both talking about the same mirror. C mirror should be fine to run exe file, but not current C# mirror. https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L520 should be changed according to C mirror, eg. *NTFS*.

@MythicManiac could you give a try with latest 1.0.0-RC3 pre-release and C mirror (not C# for the sake of testing ; also please don't use /n for now). Thanks.

**Comment by Liryna** [comment]
Change has been made https://github.com/dokan-dev/dokan-dotnet/commit/ed41f46e49bf46b022df29199de16d00d7bd5de4

**Comment by MythicManiac** [comment]
@Maxhy I tested with the C and C# mirrors with several different setups, neither seemed to be working. I'll test with the latest version when I have time and get back to you.

**Comment by MythicManiac** [comment]
Just FYI, this is still on my to-do list, although I'm not sure if I'll get back to trying again anytime soon, so closing is probably a smart idea. Will open another issue if this still persists.

**Comment by Liryna** [comment]
@MythicManiac Ah! no problem ! I tought you moved to something else 😄
